spring.application.name=real
spring.datasource.url=jdbc:h2:mem:f1db
#spring.datasource.username=sa
#spring.datasource.password=
spring.h2.console.path=/h2-con
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=false