spring.application.name=real

spring.datasource.url=jdbc:h2:mem:f1db

#spring.datasource.username=sa

#spring.datasource.password=

spring.h2.console.path=/h2

spring.h2.console.enabled=true

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.cache=false

server.port=9090

logging.level.org.springframework.security=DEBUG

app.user.username=user
app.user.password=user
app.admin.username=admin
app.admin.password=admin
app.remember-me.key=uniqueAndSecret

app.jwt.secret=&sdfgjkl-yuiopZXCvbnm5d6f7g8h9j0k1l2z3x4c5v6b7n8m9

# OAuth configuration for Keycloak
spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.client-name=Keycloak
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.client-id=sdb2026
spring.security.oauth2.client.registration.keycloak.client-secret=O2lVQPWBGKr8AVbO2qPFyqXV4PMGGG6y
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email,sdb.user,sdb.admin
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/SDB



